name: github

on:
  push:
    branches:
      - 'main'
      - 'gh-pages'
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: false
          exclude: |
            *issue
